# Generated by Django 5.0 on 2024-02-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='short_desc',
            field=models.CharField(max_length=255),
        ),
    ]
